### PR TITLE
Use DotNetZip to extract maxversion from plugin manifest

### PR DESCRIPTION
**Pull request by patrickporter**

### CODE REVIEW

**Comment by cromica** [comment]
This looks good. The only thing would be that I prefer using ZipPackage https://msdn.microsoft.com/en-us/library/system.io.packaging.zippackage(v=vs.110).aspx which comes in .NET. This way we avoid adding another external dependency for this app. What do you say?

**Comment by patrickporter** [comment]
Ok. I agree that a native library is better.  Thanks for the link. I 
should get a chance to take a look at it soon.

**Comment by patrickporter** [comment]
updated to use System.IO.Packaging.ZipPackage

**Comment by cromica** [comment]
Great. Thanks Patrick

**Pull request merged**
